### PR TITLE
Fix broken code

### PR DESCRIPTION
**Pull request by ghost**
Fix some broken code in EventHandler

### CODE REVIEW

**Comment by ghost** [comment]
Please don't use the closed pull request, as that one is from a screwed up fork.

**Comment by MCOfficer** [comment]
i'm not home ATM, but did you fetch the latest code from master? this code was intentional & working iirc

**Comment by AgentEpsilon** [comment]
Yeah, I don't think this would work at all. `rpcupdate` has the signature `rpcupdate(MinecraftRPC main, String details, ConfigHandler configHandler)`.  Not passing in the ConfigHandler should throw a compile-time error.

**Comment by MCOfficer** [comment]
FYI, i'll scrap this project. see the readme for more. thanks for trying to contribute!

**Pull request closed without merging**
